
service: app

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  test:
    handler: app/handler.test
    events:
      - httpApi:
          method: get
          path: /test