
service: app

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      convertEmptyValues: true

functions:
  test:
    handler: app/handler.test
    events:
      - httpApi:
          method: get
          path: /test

resources:
  Resources:
    DemoTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: 'DemoTable'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
